version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: brramos/nginx
    links:
    - node1:node1
    - node2:node2
    - node3:node3
    ports:
    - "80:80"
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: brramos/ubuntu_node
    links:
    - redis
    ports:
    - "8080"
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: brramos/ubuntu_node
    links:
    - redis
    ports:
    - "8080"
  node3:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: brramos/ubuntu_node
    links:
    - redis
    ports:
    - "8080"
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: brramos/redis
    ports:
    - "6379"
